---
title: "Week 1 -- SQL for Data Science"
description: |
  Notes and Exercises for the _SQL for Data Science_ course.
author:
  - name: Alexis Solis
    url: alexis.solisc@gmail.com  
    # affiliation: Spacely Sprockets
    # affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```




## Data Models Part 3: Relations vs. Transactional Models

Different relationships:

1. One-to-one.

2. Many-to-one.

3. Many-to-many.

Relational model: easy for quering and manipulating data.

Building blocks are: entity (distinct person, place, thing, or event), attributes () and relationship (association among entities)

ER Diagram Notation:

I. Chen Notation

1. One-to-one: 1:1

2. Many-to-one: 1:M

3. Many-to-many: M:N


II. Crow's Foot Notation - uses _train tracks_ (for one) and _crow's foot_ (many) for notation.

1. One-to-one: || - ||

2. Many-to-one: >- |

3. Many-to-many: >- -<


III. UML Class Diagram Notation

1. One-to-one: 1.1 - 1.1

2. Many-to-one: *.1 - 1

3. Many-to-many: 1.* - 1.*



# 06. Retrieving Data with a SELECT Statement

The 


```{sql connection=}
SELECT *

FROM Products;
```

You might to limit the number of results (sample):

```{sql connection=}

SELECT columns

FROM which_table

LIMIT no_rows_wanted --(use integers!)
```



# 07. Creating Tables


```{sql connection=}

CREATE table name_of_table


```


## Adding Data to the Table

First method. using the (implicit) `INSERT INTO` statement:


```{sql connection=}

CREATE table name_of_table


```


Second method: Using the (explicit) `INSERT INTO` statement:

```{sql connection=}
INSERT INTO Shoes
(Id,
,Brand
,Type
,Color
,Price
,Desc
)

VALUES
(

)

```

# 08. Creating a Temporary Table

First of all, the most important thing to know about these temporary tables is that these will be deleted when the current client session is terminated. That's why they're called temporary tables. 




```{sql connection=}

CREATE TEMPORARY TABLE  name_of_table AS
(
  SELECT *
  FROM shoes
  WHERE shoe_type = 'sandals'

)

```


# 09. Adding Comments


```{sql connection=}

CREATE TEMPORARY TABLE  name_of_table AS
(
  SELECT *
  FROM shoes
 -- WHERE shoe_type = 'sandals'

)

```


```{sql connection=}

CREATE TEMPORARY TABLE  name_of_table AS
(
 /* 
 
 SELECT *
 
 FROM shoes
 
 */
 WHERE shoe_type = 'sandals'

)

```





This module's primary focus was to introduce the world of SQL to you and to get you started with a few simple querying techniques. Attached to this posting, are a few good, quality overviews of SQL that go into a little bit more depth than what we can cover in our lecture videos. I encourage you to check out and review one or more of these resources.

What is SQL and How is it Used?
https://www.thebalancecareers.com/what-is-sql-and-uses-2071909

NTC Hosting: Structured Query Language (it's worth exploring this site, not just this singular posting)
https://www.ntchosting.com/encyclopedia/databases/structured-query-language/

SQLite Tutorial
https://www.tutorialspoint.com/sqlite/index.htm


We introduced ER diagrams and the concept of database modeling in this module. Naturally, these are deep topics and we barely scratched the surface in our lecture videos. I encourage you to review some of the resources below to learn more about these topics in more depth.



Norwalk Aberdeen: Entity-Relationsip Diagrams (9 Minute YouTube Video)
https://www.youtube.com/watch?v=c0_9Y8QAstg

Star Schema vs. Snowflake Schema
www.vertabelo.com/blog/technical-articles/data-warehouse-modeling-star-schema-vs-snowflake-schema

Explain Star Schema & Snow Flake Design (5 Minute YouTube Video)
https://www.youtube.com/watch?v=KUwOcip7Zzc

Data Modeling 101
http://www.agiledata.org/essays/dataModeling101.html

What is Data Modeling - An Introduction for Business Analysts
http://business-analysis-excellence.com/what-is-data-modeling/

Wikipedia: Data Modeling
https://en.wikipedia.org/wiki/Data_modeling


Read the following articles and find two additional articles to read describing the differences between NoSQL and SQL, then form an opinion as to whether or not SQL will still be relevant in a big data world. Please state your newly found sources and how you came to your conclusion.



Dataconomy: SQL vs. NoSQL - What You Need to Know
http://dataconomy.com/2014/07/sql-vs-nosql-need-know/

TechRepublic: NoSQL keeps rising, but relational databases still dominate big data
https://www.techrepublic.com/article/nosql-keeps-rising-but-relational-databases-still-dominate-big-data/

SiliconRepublic: Data Science Skills: Is NoSQL Better than SQL?
https://www.siliconrepublic.com/careers/data-science-skills-sql

SQL vs NoSQL: 5 Critical Differences (https://www.xplenty.com/blog/the-sql-vs-nosql-difference/)

Why SQL is beating NoSQL, and what this means for the future of data (https://blog.timescale.com/blog/why-sql-beating-nosql-what-this-means-for-future-of-data-time-series-database-348b777b847a/)

MapReduce: A major step backward (https://homes.cs.washington.edu/~billhowe/mapreduce_a_major_step_backwards.html)








